### ISSUE TITLE
Broken example?

### ISSUE THREAD

**Issue by Erotemic** [PatrickMassot/GlimpseOfLean#5]
This is 90% a me problem given my unfamiliarity with lean, but on the 10% chance it is a mistake in the repo: 

For some reason I was unable to get the repo itself working, but the examples seemed standalone so I imagine they would work if they were pasted into a working lean project

Following the example in https://github.com/PatrickMassot/GlimpseOfLean/blob/master/GlimpseOfLean/Exercises/01Rewriting.lean#L155

When I write the code:

```
import Mathlib
import Lake
open Filter 

example (a b c d : ℝ) (h : c = d*a - b) (h' : b = a*d) : c = 0 := by {
  rw [h'] at h
  ring at h
  -- Our assumption `h` is now exactly what we have to prove
  exact h
}
```

I got an error:

```
unexpected token 'at'; expected '}'
```

**Comment by pitmonticone** [comment]
Hi @Erotemic, the reason why the example: 

```lean
import Mathlib
import Lake
open Filter 

example (a b c d : ℝ) (h : c = d*a - b) (h' : b = a*d) : c = 0 := by {
  rw [h'] at h
  ring at h
  -- Our assumption `h` is now exactly what we have to prove
  exact h
}
```

returns the error: 

```error
unexpected token 'at'; expected '}'
```

but it works perfectly fine in [`01Rewriting.lean`](https://github.com/PatrickMassot/GlimpseOfLean/blob/master/GlimpseOfLean/Exercises/01Rewriting.lean#L155) is just because `01Rewriting.lean` imports the custom library [`GlimpseOfLean.Library.Basic`](https://github.com/PatrickMassot/GlimpseOfLean/blob/master/GlimpseOfLean/Library/Basic.lean) where the `at` tactic modifier is implemented.

**Comment by PatrickMassot** [comment]
I am sorry this was confusing. There was a reason for this deviation from usual Mathlib, but not a very good one. So I removed this trick.
